Fix dockerfile to build vep, conda, R, and samtools and submit image to elstonndsouza/docker-vutr-pipeline

diff --git a/pipeline/Dockerfile b/pipeline/Dockerfile
--- a/pipeline/Dockerfile
+++ b/pipeline/Dockerfile
@@ -1,45 +1,220 @@
-# Not working
 # Create a dockerfile with the following dependencies 
 # to run the pipeline reproducibly
 
-FROM alpine:latest
+# To build and install and send to dockerhub
 
-# Install system dependencies for VEP, R and Bioconductor
-RUN apk update && \
-    apk upgrade && \
-    apk add --no-cache perl wget unzip R R-dev make gcc g++ libxml2 libxml2-dev curl perl-dbd-mysql
-# Install VEP
-RUN wget https://github.com/Ensembl/ensembl-vep/archive/refs/tags/release/104.0.tar.gz && \
-    tar -zxvf 104.0.tar.gz && \
-    mv ensembl-vep-release-104.0 vep && \
-    rm 104.0.tar.gz && \
-    cd vep && \
-    perl INSTALL.pl --AUTO cpanminus && \
-    perl INSTALL.pl --AUTO Tools && \
-    cd ..
+# docker build -t docker-vutr-pipeline -f Dockerfile .
+# docker tag docker-vutr-pipeline elstonndsouza/docker-vutr-pipeline
+# docker push elstonndsouza/docker-vutr-pipeline:latest
 
-# Install Conda
-RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh -O miniconda.sh && \
-    /bin/sh miniconda.sh -bfp /usr/local && \
-    rm miniconda.sh && \
-    /usr/local/bin/conda clean -tipsy && \
-    ln -s /usr/local/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
-    echo ". /usr/local/etc/profile.d/conda.sh" >> ~/.bashrc && \
-    echo "conda activate base" >> ~/.bashrc
 
-# Copy the environment.yml file into the container
-COPY pipeline-env.yaml .
+###################################################
+# Stage 1 - docker container to build ensembl-vep #
+###################################################
+FROM ubuntu:18.04 as builder
 
-# Create a new Conda environment based on the environment file
-RUN /opt/conda/bin/conda env create -f pipeline-env.yaml && \
-    /opt/conda/bin/conda clean -afy && \
-    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
-    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.profile && \
-    echo "conda activate vep-r" >> ~/.profile
+# Update aptitude and install some required packages
+# a lot of them are required for Bio::DB::BigFile
+RUN apt-get update && apt-get -y install \
+    build-essential \
+    git \
+    libpng-dev \
+    zlib1g-dev \
+    libbz2-dev \
+    liblzma-dev \
+    perl \
+    perl-base \
+    unzip \
+    wget && \
+    rm -rf /var/lib/apt/lists/*
+
+# Setup VEP environment
+ENV OPT /opt/vep
+ENV OPT_SRC $OPT/src
+ENV HTSLIB_DIR $OPT_SRC/htslib
+ENV BRANCH release/104
+
+# Working directory
+WORKDIR $OPT_SRC
+
+# Clone/download repositories/libraries
+RUN if [ "$BRANCH" = "master" ]; \
+    then export BRANCH_OPT=""; \
+    else export BRANCH_OPT="-b $BRANCH"; \
+    fi && \
+    # Get ensembl cpanfile in order to get the list of the required Perl libraries
+    wget -q "https://raw.githubusercontent.com/Ensembl/ensembl/$BRANCH/cpanfile" -O "ensembl_cpanfile" && \
+    # Clone ensembl-vep git repository
+    git clone $BRANCH_OPT --depth 1 https://github.com/Ensembl/ensembl-vep.git && chmod u+x ensembl-vep/*.pl && \
+    # Clone ensembl-variation git repository and compile C code
+    git clone $BRANCH_OPT --depth 1 https://github.com/Ensembl/ensembl-variation.git && \
+    mkdir var_c_code && \
+    cp ensembl-variation/C_code/*.c ensembl-variation/C_code/Makefile var_c_code/ && \
+    rm -rf ensembl-variation && \
+    chmod u+x var_c_code/* && \
+    # Clone bioperl-ext git repository - used by Haplosaurus
+    git clone --depth 1 https://github.com/bioperl/bioperl-ext.git && \
+    # Download ensembl-xs - it contains compiled versions of certain key subroutines used in VEP
+    wget https://github.com/Ensembl/ensembl-xs/archive/2.3.2.zip -O ensembl-xs.zip && \
+    unzip -q ensembl-xs.zip && mv ensembl-xs-2.3.2 ensembl-xs && rm -rf ensembl-xs.zip && \
+    # Clone/Download other repositories: bioperl-live is needed so the cpanm dependencies installation from the ensembl-vep/cpanfile file takes less disk space
+    ensembl-vep/travisci/get_dependencies.sh && \
+    # Only keep the bioperl-live "Bio" library
+    mv bioperl-live bioperl-live_bak && mkdir bioperl-live && mv bioperl-live_bak/Bio bioperl-live/ && rm -rf bioperl-live_bak && \
+    ## A lot of cleanup on the imported libraries, in order to reduce the docker image ##
+    rm -rf Bio-HTS/.??* Bio-HTS/Changes Bio-HTS/DISCLAIMER Bio-HTS/MANIFEST* Bio-HTS/README Bio-HTS/scripts Bio-HTS/t Bio-HTS/travisci \
+           bioperl-ext/.??* bioperl-ext/Bio/SeqIO bioperl-ext/Bio/Tools bioperl-ext/Makefile.PL bioperl-ext/README* bioperl-ext/t bioperl-ext/examples \
+           ensembl-vep/.??* ensembl-vep/docker \
+           ensembl-xs/.??* ensembl-xs/TODO ensembl-xs/Changes ensembl-xs/INSTALL ensembl-xs/MANIFEST ensembl-xs/README ensembl-xs/t ensembl-xs/travisci \
+           htslib/.??* htslib/INSTALL htslib/NEWS htslib/README* htslib/test && \
+    # Only keep needed kent-335_base libraries for VEP - used by Bio::DB::BigFile (bigWig parsing)
+    mv kent-335_base kent-335_base_bak && mkdir -p kent-335_base/src && \
+    cp -R kent-335_base_bak/src/lib kent-335_base_bak/src/inc kent-335_base_bak/src/jkOwnLib kent-335_base/src/ && \
+    cp kent-335_base_bak/src/*.sh kent-335_base/src/ && \
+    rm -rf kent-335_base_bak
+
+# Setup bioperl-ext
+WORKDIR bioperl-ext/Bio/Ext/Align/
+RUN perl -pi -e"s|(cd libs.+)CFLAGS=\\\'|\$1CFLAGS=\\\'-fPIC |" Makefile.PL
+
+# Install htslib binaries (for 'bgzip' and 'tabix')
+# htslib requires the packages 'zlib1g-dev', 'libbz2-dev' and 'liblzma-dev'
+WORKDIR $HTSLIB_DIR
+RUN make install && rm -f Makefile *.c
+
+# Compile Variation LD C scripts
+WORKDIR $OPT_SRC/var_c_code
+RUN make && rm -f Makefile *.c
+
+
+###################################################
+# Stage 2 - docker container to build ensembl-vep #
+###################################################
+FROM ubuntu:18.04
+
+# Update aptitude and install some required packages
+# a lot of them are required for Bio::DB::BigFile
+RUN apt-get update && apt-get -y install \
+    build-essential \
+    cpanminus \
+    curl \
+    libmysqlclient-dev \
+    libpng-dev \
+    libssl-dev \
+    zlib1g-dev \
+    libbz2-dev \
+    liblzma-dev \
+    locales \
+    openssl \
+    perl \
+    perl-base \
+    unzip \
+    vim && \
+    apt-get -y purge manpages-dev && \
+    apt-get clean && \
+    rm -rf /var/lib/apt/lists/*
+
+# Setup VEP environment
+ENV OPT /opt/vep
+ENV OPT_SRC $OPT/src
+ENV PERL5LIB_TMP $PERL5LIB:$OPT_SRC/ensembl-vep:$OPT_SRC/ensembl-vep/modules
+ENV PERL5LIB $PERL5LIB_TMP:$OPT_SRC/bioperl-live
+ENV KENT_SRC $OPT/src/kent-335_base/src
+ENV HTSLIB_DIR $OPT_SRC/htslib
+ENV MACHTYPE x86_64
+ENV DEPS $OPT_SRC
+ENV PATH $OPT_SRC/ensembl-vep:$OPT_SRC/var_c_code:$PATH
+ENV LANG_VAR en_US.UTF-8
+
+# Create vep user
+RUN useradd -r -m -U -d "$OPT" -s /bin/bash -c "VEP User" -p '' vep && usermod -a -G sudo vep && mkdir -p $OPT_SRC
+USER vep
+
+# Copy downloaded libraries (stage 1) to this image (stage 2)
+COPY --chown=vep:vep --from=builder $OPT_SRC $OPT_SRC
+#############################################################
+
+# Change user to root for the following complilations/installations
+USER root
+
+# Install bioperl-ext, faster alignments for haplo (XS-based BioPerl extensions to C libraries)
+WORKDIR $OPT_SRC/bioperl-ext/Bio/Ext/Align/
+RUN perl Makefile.PL && make && make install && rm -f Makefile*
+
+# Install ensembl-xs, faster run using re-implementation in C of some of the Perl subroutines
+WORKDIR $OPT_SRC/ensembl-xs
+RUN perl Makefile.PL && make && make install && rm -f Makefile* cpanfile
+
+WORKDIR $OPT_SRC
+# Install/compile more libraries
+RUN ensembl-vep/travisci/build_c.sh && \
+    # Remove unused Bio-DB-HTS files
+    rm -rf Bio-HTS/cpanfile Bio-HTS/Build.PL Bio-HTS/Build Bio-HTS/_build Bio-HTS/INSTALL.pl && \
+    # Install ensembl perl dependencies (cpanm)
+    cpanm --installdeps --with-recommends --notest --cpanfile ensembl_cpanfile . && \
+    cpanm --installdeps --with-recommends --notest --cpanfile ensembl-vep/cpanfile . && \
+    # Delete bioperl and cpanfiles after the cpanm installs as bioperl will be reinstalled by the INSTALL.pl script
+    rm -rf bioperl-live ensembl_cpanfile ensembl-vep/cpanfile && \
+    # Configure "locale", see https://github.com/rocker-org/rocker/issues/19
+    echo "$LANG_VAR UTF-8" >> /etc/locale.gen && locale-gen en_US.utf8 && \
+    /usr/sbin/update-locale LANG=$LANG_VAR && \
+    # Copy htslib executables. It also requires the packages 'zlib1g-dev', 'libbz2-dev' and 'liblzma-dev'
+    cp $HTSLIB_DIR/bgzip $HTSLIB_DIR/tabix $HTSLIB_DIR/htsfile /usr/local/bin/
+
+ENV LC_ALL $LANG_VAR
+ENV LANG $LANG_VAR
+
+# Switch back to vep user
+USER vep
+ENV PERL5LIB $PERL5LIB_TMP
+
+# Final steps
+WORKDIR $OPT_SRC/ensembl-vep
+# Update bash profile
+RUN echo >> $OPT/.profile && \
+    echo PATH=$PATH:\$PATH >> $OPT/.profile && \
+    echo export PATH >> $OPT/.profile && \
+    # Run INSTALL.pl and remove the ensemb-vep tests and travis
+    ./INSTALL.pl -a a -l -n && rm -rf t travisci .travis.yml
+
+# Install conda and R
+USER root
+
+RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime
+
+RUN apt-get update && \
+    apt-get install -y r-base r-base-dev
 
 # Install R packages from CRAN and Bioconductor
-RUN R -e "install.packages(c('magrittr', 'data.table'), repos='https://cran.rstudio.com/')" && \
-    R -e "if (!requireNamespace('BiocManager', quietly = TRUE)) install.packages('BiocManager')" && \
+RUN R -e "install.packages(c('magrittr', 'data.table', 'BiocManager'), repos='https://cran.rstudio.com/')" && \
     R -e "BiocManager::install(c('rtracklayer'))"
 
-ENV PATH /opt/conda/bin:$PATH
+COPY --from=continuumio/miniconda3:4.12.0 /opt/conda /opt/conda
+
+ENV PATH=/opt/conda/bin:$PATH
+
+# Usage examples
+RUN set -ex && \
+    conda config --set always_yes yes --set changeps1 no && \
+    conda info -a && \
+    conda config --add channels conda-forge && \
+    conda install --quiet --freeze-installed -c main conda-pack &&\
+    conda init bash 
+
+WORKDIR /root 
+
+# Copy the environment.yml
+# file into the container
+COPY vutr-pipeline-env.yml .
+
+# # # Create a new Conda 
+# # # environment based on the environment file
+RUN conda env update -n base -f vutr-pipeline-env.yml --prune && \
+    conda clean -afy && \
+    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
+    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.profile
+
+# Install bedtools, htslib and samtools, bedtools 
+# and other dependencies
+RUN apt-get update && \
+    apt-get install -y samtools tabix bcftools bedtools \
