Add named inputs

diff --git a/pipeline/src/variants/query_datasets b/pipeline/src/variants/query_datasets
--- a/pipeline/src/variants/query_datasets
+++ b/pipeline/src/variants/query_datasets
@@ -1,66 +1,88 @@
 #!/bin/sh
 # This script filters a VCF file using tabix and saves the results as a TSV file
-# The script takes three arguments:
-# 1. The input VCF file
-# 2. The output TSV file
-# 3. The region file to use for filtering
-# 4. The type of data (gnomad or clinvar)
+# The script takes four arguments as named variables:
+# -i/--input_file: The input VCF file
+# -o/--output_file: The output TSV file
+# -r/--region_file: The region file to use for filtering
+# -t/--data_type: The type of data (gnomad or clinvar)
 
-# Running the file 
+# Define the usage message
+usage="Usage: $(basename $0) -i|--input_file <input_file> -o|--output_file <output_file> -r|--region_file <region_file> -t|--data_type <gnomad|clinvar>"
 
+# Parse command-line arguments
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -i|--input_file)
+      input_file="$2"
+      shift 2
+      ;;
+    -o|--output_file)
+      output_file="$2"
+      shift 2
+      ;;
+    -r|--region_file)
+      region_file="$2"
+      shift 2
+      ;;
+    -t|--data_type)
+      data_type="$2"
+      shift 2
+      ;;
+    -v|--output_vcf)
+      output_vcf="$2"
+      shift 2
+      ;;
+    *)
+      echo "Invalid argument: $1"
+      echo $usage
+      exit 1
+      ;;
+  esac
+done
 
-# Check if the input file argument was provided
-if [ $# -lt 3 ]; then
-    echo "Usage: $0 input_file output_file tabix_region_file type"
-    exit 1
+# Check if all required arguments are provided
+if [ -z "$input_file" ] || [ -z "$output_file" ] || [ -z "$region_file" ] || [ -z "$data_type" ]; then
+  echo "Missing arguments"
+  echo $usage
+  exit 1
 fi
-
-# Get the input file path from the command-line argument
-input=$1
 
 # Check if the input file exists
-if [ ! -f "$input" ]; then
-    echo "Input file not found: $input"
+if [ ! -f "$input_file" ]; then
+    echo "Input file not found: $input_file"
     exit 1
 fi
 
-# Get the output file path from the command-line argument
-output=$2
-
-# First check if the output file already exists
-if [ -f "$output" ]; then
-    echo "Output file already exists: $output"
+# Check if the output file already exists
+if [ -f "$output_file" ]; then
+    echo "Output file already exists: $output_file"
     exit 1
 fi
 
-# Get the region file path from the command-line argument
-region=$3
-
-# Get the type argument
-type=$4
 
 # Define the headers for the output TSV file
-if [ "$type" = "gnomad" ]; then
+if [ "$data_type" = "gnomad" ]; then
     # If type is gnomad, then we need to add the following headers
     # NOTE:
     # We require the following headers from gnomAD
     # CHROM, POS, ID, HGVSC, INFO/AC, INFO/AN, INFO/AF, INFO/vep, INFO/variant_type
-    headers='chrom\tpos\tref\talt\tid\tac\tan\taf\tvep\tvariant_type'
+    headers='chrom\tpos\tref\talt\tvariant_id\tac\tan\taf\tvep\tvariant_type'
     query_string='%CHROM\t%POS\t%REF\t%ALT\t%ID\t%INFO/AC\t%INFO/AN\t%INFO/AF\t%INFO/vep\t%INFO/variant_type\n'
 # Otherwise if clinvar, then we need to add the following headers
-elif [ "$type" = 'clinvar' ]; then
+elif [ "$data_type" = 'clinvar' ]; then
     # NOTE:
     # We require the following headers from ClinVar
     # CHROM, POS, REF, ALT, ID, CLNSIG, CLNREVSTAT, CLNDN, CLNDISDB, CLNVC, CLNHGVS, CLNVI
-    headers='chrom\tpos\tref\talt\tid\tclnsig\tclnrevstat\tclndn\tclndisdb\tclnvc\tclnhgvs\tclnvi'
+    headers='chrom\tpos\tref\talt\tvariant_id\tclnsig\tclnrevstat\tclndn\tclndisdb\tclnvc\tclnhgvs\tclnvi'
     query_string='%CHROM\t%POS\t%REF\t%ALT\t%ID\t%INFO/CLNSIG\t%INFO/CLNREVSTAT\t%INFO/CLNDN\t%INFO/CLNDISDB\t%INFO/CLNVC\t%INFO/CLNHGVS\t%INFO/CLNVI\n'
 else
-    echo "Invalid type argument: $type"
+    echo "Invalid type argument: $data_type"
     exit 1
 fi
 
 # Filter using tabix using the specified region file 
 # and perform query save to the output file
-echo -e $headers > $output && tabix -h $input -R $region | bcftools query -f $query_string >> $output
+echo -e $headers > $output_file && tabix -h $input_file -R $region_file > $output_vcf
+bcftools query -f $query_string $output_vcf >> $output_file
 
-echo "Filtered TSV file saved to $output"
+echo "Filtered TSV file saved to $output_file"
